// <auto-generated />
using System;
using ImobiAPI.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ImobiAPI.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260523202031_AddUsoApiKeys")]
    partial class AddUsoApiKeys
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ImobiAPI.Domain.Entities.AliquotaITBI", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Aliquota")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)")
                        .HasColumnName("aliquota");

                    b.Property<decimal?>("AliquotaFinanciado")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)")
                        .HasColumnName("aliquota_financiado");

                    b.Property<int>("AnoVigencia")
                        .HasColumnType("integer")
                        .HasColumnName("ano_vigencia");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<string>("FonteLegal")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("fonte_legal");

                    b.Property<decimal?>("LimiteIsencao")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("limite_isencao");

                    b.Property<int>("MunicipioId")
                        .HasColumnType("integer")
                        .HasColumnName("municipio_id");

                    b.HasKey("Id");

                    b.HasIndex("MunicipioId")
                        .IsUnique();

                    b.ToTable("aliquotas_itbi", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Aliquota = 3.0m,
                            AnoVigencia = 2024,
                            Ativo = true,
                            FonteLegal = "Lei 11.154/1991",
                            MunicipioId = 1
                        },
                        new
                        {
                            Id = 2,
                            Aliquota = 3.0m,
                            AnoVigencia = 2024,
                            Ativo = true,
                            FonteLegal = "Lei 691/1984",
                            MunicipioId = 2
                        },
                        new
                        {
                            Id = 3,
                            Aliquota = 3.0m,
                            AnoVigencia = 2024,
                            Ativo = true,
                            FonteLegal = "Lei 5.839/1991",
                            MunicipioId = 3
                        },
                        new
                        {
                            Id = 4,
                            Aliquota = 2.0m,
                            AnoVigencia = 2024,
                            Ativo = true,
                            FonteLegal = "Lei 4.279/1990",
                            MunicipioId = 4
                        },
                        new
                        {
                            Id = 5,
                            Aliquota = 3.0m,
                            AnoVigencia = 2024,
                            Ativo = true,
                            FonteLegal = "Lei 3.830/2006",
                            MunicipioId = 5
                        },
                        new
                        {
                            Id = 6,
                            Aliquota = 2.7m,
                            AnoVigencia = 2024,
                            Ativo = true,
                            FonteLegal = "Lei 13.250/2009",
                            MunicipioId = 6
                        },
                        new
                        {
                            Id = 7,
                            Aliquota = 2.0m,
                            AnoVigencia = 2024,
                            Ativo = true,
                            FonteLegal = "Lei 1.815/2013",
                            MunicipioId = 7
                        },
                        new
                        {
                            Id = 8,
                            Aliquota = 2.0m,
                            AnoVigencia = 2024,
                            Ativo = true,
                            FonteLegal = "Lei 16.314/1997",
                            MunicipioId = 8
                        },
                        new
                        {
                            Id = 9,
                            Aliquota = 3.0m,
                            AnoVigencia = 2024,
                            Ativo = true,
                            FonteLegal = "Lei 7.531/1994",
                            MunicipioId = 9
                        },
                        new
                        {
                            Id = 10,
                            Aliquota = 2.0m,
                            AnoVigencia = 2024,
                            Ativo = true,
                            FonteLegal = "Lei 8.492/2000",
                            MunicipioId = 10
                        });
                });

            modelBuilder.Entity("ImobiAPI.Domain.Entities.ApiKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativa");

                    b.Property<string>("Chave")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("chave");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<int>("LimiteDiario")
                        .HasColumnType("integer")
                        .HasColumnName("limite_diario");

                    b.Property<string>("Plano")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("plano");

                    b.HasKey("Id");

                    b.HasIndex("Chave")
                        .IsUnique();

                    b.ToTable("api_keys", (string)null);
                });

            modelBuilder.Entity("ImobiAPI.Domain.Entities.FaixaEmolumento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("PercentualExcedente")
                        .HasPrecision(6, 4)
                        .HasColumnType("numeric(6,4)")
                        .HasColumnName("percentual_excedente");

                    b.Property<int>("TabelaEmolumentosId")
                        .HasColumnType("integer")
                        .HasColumnName("tabela_id");

                    b.Property<string>("TipoAto")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo_ato");

                    b.Property<decimal>("ValorFixo")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("valor_fixo");

                    b.Property<decimal?>("ValorMaximo")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("valor_maximo");

                    b.Property<decimal>("ValorMinimo")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("valor_minimo");

                    b.HasKey("Id");

                    b.HasIndex("TabelaEmolumentosId");

                    b.ToTable("faixas_emolumentos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            TabelaEmolumentosId = 1,
                            TipoAto = "Escritura",
                            ValorFixo = 1500m,
                            ValorMaximo = 100000m,
                            ValorMinimo = 0m
                        },
                        new
                        {
                            Id = 2,
                            TabelaEmolumentosId = 1,
                            TipoAto = "Escritura",
                            ValorFixo = 3000m,
                            ValorMaximo = 500000m,
                            ValorMinimo = 100000.01m
                        },
                        new
                        {
                            Id = 3,
                            TabelaEmolumentosId = 1,
                            TipoAto = "Escritura",
                            ValorFixo = 6000m,
                            ValorMinimo = 500000.01m
                        },
                        new
                        {
                            Id = 4,
                            TabelaEmolumentosId = 2,
                            TipoAto = "Registro",
                            ValorFixo = 1000m,
                            ValorMaximo = 100000m,
                            ValorMinimo = 0m
                        },
                        new
                        {
                            Id = 5,
                            TabelaEmolumentosId = 2,
                            TipoAto = "Registro",
                            ValorFixo = 2000m,
                            ValorMaximo = 500000m,
                            ValorMinimo = 100000.01m
                        },
                        new
                        {
                            Id = 6,
                            TabelaEmolumentosId = 2,
                            TipoAto = "Registro",
                            ValorFixo = 4000m,
                            ValorMinimo = 500000.01m
                        },
                        new
                        {
                            Id = 7,
                            TabelaEmolumentosId = 5,
                            TipoAto = "Escritura",
                            ValorFixo = 1200m,
                            ValorMaximo = 100000m,
                            ValorMinimo = 0m
                        },
                        new
                        {
                            Id = 8,
                            TabelaEmolumentosId = 5,
                            TipoAto = "Escritura",
                            ValorFixo = 2500m,
                            ValorMaximo = 500000m,
                            ValorMinimo = 100000.01m
                        },
                        new
                        {
                            Id = 9,
                            TabelaEmolumentosId = 5,
                            TipoAto = "Escritura",
                            ValorFixo = 5000m,
                            ValorMinimo = 500000.01m
                        },
                        new
                        {
                            Id = 10,
                            TabelaEmolumentosId = 6,
                            TipoAto = "Registro",
                            ValorFixo = 800m,
                            ValorMaximo = 100000m,
                            ValorMinimo = 0m
                        },
                        new
                        {
                            Id = 11,
                            TabelaEmolumentosId = 6,
                            TipoAto = "Registro",
                            ValorFixo = 1800m,
                            ValorMaximo = 500000m,
                            ValorMinimo = 100000.01m
                        },
                        new
                        {
                            Id = 12,
                            TabelaEmolumentosId = 6,
                            TipoAto = "Registro",
                            ValorFixo = 3500m,
                            ValorMinimo = 500000.01m
                        },
                        new
                        {
                            Id = 13,
                            TabelaEmolumentosId = 3,
                            TipoAto = "Escritura",
                            ValorFixo = 1400m,
                            ValorMaximo = 100000m,
                            ValorMinimo = 0m
                        },
                        new
                        {
                            Id = 14,
                            TabelaEmolumentosId = 3,
                            TipoAto = "Escritura",
                            ValorFixo = 2800m,
                            ValorMaximo = 500000m,
                            ValorMinimo = 100000.01m
                        },
                        new
                        {
                            Id = 15,
                            TabelaEmolumentosId = 3,
                            TipoAto = "Escritura",
                            ValorFixo = 5500m,
                            ValorMinimo = 500000.01m
                        },
                        new
                        {
                            Id = 16,
                            TabelaEmolumentosId = 4,
                            TipoAto = "Registro",
                            ValorFixo = 900m,
                            ValorMaximo = 100000m,
                            ValorMinimo = 0m
                        },
                        new
                        {
                            Id = 17,
                            TabelaEmolumentosId = 4,
                            TipoAto = "Registro",
                            ValorFixo = 1900m,
                            ValorMaximo = 500000m,
                            ValorMinimo = 100000.01m
                        },
                        new
                        {
                            Id = 18,
                            TabelaEmolumentosId = 4,
                            TipoAto = "Registro",
                            ValorFixo = 3800m,
                            ValorMinimo = 500000.01m
                        },
                        new
                        {
                            Id = 19,
                            TabelaEmolumentosId = 7,
                            TipoAto = "Escritura",
                            ValorFixo = 2000m,
                            ValorMinimo = 0m
                        },
                        new
                        {
                            Id = 20,
                            TabelaEmolumentosId = 8,
                            TipoAto = "Registro",
                            ValorFixo = 1500m,
                            ValorMinimo = 0m
                        },
                        new
                        {
                            Id = 21,
                            TabelaEmolumentosId = 9,
                            TipoAto = "Escritura",
                            ValorFixo = 2200m,
                            ValorMinimo = 0m
                        },
                        new
                        {
                            Id = 22,
                            TabelaEmolumentosId = 10,
                            TipoAto = "Registro",
                            ValorFixo = 1600m,
                            ValorMinimo = 0m
                        },
                        new
                        {
                            Id = 23,
                            TabelaEmolumentosId = 11,
                            TipoAto = "Escritura",
                            ValorFixo = 1900m,
                            ValorMinimo = 0m
                        },
                        new
                        {
                            Id = 24,
                            TabelaEmolumentosId = 12,
                            TipoAto = "Registro",
                            ValorFixo = 1400m,
                            ValorMinimo = 0m
                        },
                        new
                        {
                            Id = 25,
                            TabelaEmolumentosId = 13,
                            TipoAto = "Escritura",
                            ValorFixo = 1800m,
                            ValorMinimo = 0m
                        },
                        new
                        {
                            Id = 26,
                            TabelaEmolumentosId = 14,
                            TipoAto = "Registro",
                            ValorFixo = 1300m,
                            ValorMinimo = 0m
                        },
                        new
                        {
                            Id = 27,
                            TabelaEmolumentosId = 15,
                            TipoAto = "Escritura",
                            ValorFixo = 1700m,
                            ValorMinimo = 0m
                        },
                        new
                        {
                            Id = 28,
                            TabelaEmolumentosId = 16,
                            TipoAto = "Registro",
                            ValorFixo = 1200m,
                            ValorMinimo = 0m
                        },
                        new
                        {
                            Id = 29,
                            TabelaEmolumentosId = 17,
                            TipoAto = "Escritura",
                            ValorFixo = 2100m,
                            ValorMinimo = 0m
                        },
                        new
                        {
                            Id = 30,
                            TabelaEmolumentosId = 18,
                            TipoAto = "Registro",
                            ValorFixo = 1500m,
                            ValorMinimo = 0m
                        },
                        new
                        {
                            Id = 31,
                            TabelaEmolumentosId = 19,
                            TipoAto = "Escritura",
                            ValorFixo = 1600m,
                            ValorMinimo = 0m
                        },
                        new
                        {
                            Id = 32,
                            TabelaEmolumentosId = 20,
                            TipoAto = "Registro",
                            ValorFixo = 1100m,
                            ValorMinimo = 0m
                        });
                });

            modelBuilder.Entity("ImobiAPI.Domain.Entities.Municipio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.Property<int?>("Populacao")
                        .HasColumnType("integer")
                        .HasColumnName("populacao");

                    b.Property<bool>("Suportado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("suportado");

                    b.Property<string>("UF")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("uf");

                    b.HasKey("Id");

                    b.ToTable("municipios", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AtualizadoEm = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "São Paulo",
                            Populacao = 12325232,
                            Suportado = true,
                            UF = "SP"
                        },
                        new
                        {
                            Id = 2,
                            AtualizadoEm = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Rio de Janeiro",
                            Populacao = 6748000,
                            Suportado = true,
                            UF = "RJ"
                        },
                        new
                        {
                            Id = 3,
                            AtualizadoEm = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Belo Horizonte",
                            Populacao = 2722000,
                            Suportado = true,
                            UF = "MG"
                        },
                        new
                        {
                            Id = 4,
                            AtualizadoEm = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Salvador",
                            Populacao = 2886698,
                            Suportado = true,
                            UF = "BA"
                        },
                        new
                        {
                            Id = 5,
                            AtualizadoEm = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Brasília",
                            Populacao = 3094325,
                            Suportado = true,
                            UF = "DF"
                        },
                        new
                        {
                            Id = 6,
                            AtualizadoEm = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Curitiba",
                            Populacao = 1948626,
                            Suportado = true,
                            UF = "PR"
                        },
                        new
                        {
                            Id = 7,
                            AtualizadoEm = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Manaus",
                            Populacao = 2219580,
                            Suportado = true,
                            UF = "AM"
                        },
                        new
                        {
                            Id = 8,
                            AtualizadoEm = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Recife",
                            Populacao = 1653461,
                            Suportado = true,
                            UF = "PE"
                        },
                        new
                        {
                            Id = 9,
                            AtualizadoEm = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Porto Alegre",
                            Populacao = 1488252,
                            Suportado = true,
                            UF = "RS"
                        },
                        new
                        {
                            Id = 10,
                            AtualizadoEm = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nome = "Fortaleza",
                            Populacao = 2703391,
                            Suportado = true,
                            UF = "CE"
                        });
                });

            modelBuilder.Entity("ImobiAPI.Domain.Entities.TabelaEmolumentos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AnoVigencia")
                        .HasColumnType("integer")
                        .HasColumnName("ano_vigencia");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<string>("FonteTJ")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("fonte_tj");

                    b.Property<string>("TipoAto")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo_ato");

                    b.Property<string>("UF")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("uf");

                    b.HasKey("Id");

                    b.HasIndex("UF", "AnoVigencia", "TipoAto")
                        .IsUnique();

                    b.ToTable("tabelas_emolumentos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AnoVigencia = 2024,
                            Ativo = true,
                            FonteTJ = "TJ-SP",
                            TipoAto = "Escritura",
                            UF = "SP"
                        },
                        new
                        {
                            Id = 2,
                            AnoVigencia = 2024,
                            Ativo = true,
                            FonteTJ = "TJ-SP",
                            TipoAto = "Registro",
                            UF = "SP"
                        },
                        new
                        {
                            Id = 3,
                            AnoVigencia = 2024,
                            Ativo = true,
                            FonteTJ = "TJ-RJ",
                            TipoAto = "Escritura",
                            UF = "RJ"
                        },
                        new
                        {
                            Id = 4,
                            AnoVigencia = 2024,
                            Ativo = true,
                            FonteTJ = "TJ-RJ",
                            TipoAto = "Registro",
                            UF = "RJ"
                        },
                        new
                        {
                            Id = 5,
                            AnoVigencia = 2024,
                            Ativo = true,
                            FonteTJ = "TJ-MG",
                            TipoAto = "Escritura",
                            UF = "MG"
                        },
                        new
                        {
                            Id = 6,
                            AnoVigencia = 2024,
                            Ativo = true,
                            FonteTJ = "TJ-MG",
                            TipoAto = "Registro",
                            UF = "MG"
                        },
                        new
                        {
                            Id = 7,
                            AnoVigencia = 2024,
                            Ativo = true,
                            FonteTJ = "TJ-BA",
                            TipoAto = "Escritura",
                            UF = "BA"
                        },
                        new
                        {
                            Id = 8,
                            AnoVigencia = 2024,
                            Ativo = true,
                            FonteTJ = "TJ-BA",
                            TipoAto = "Registro",
                            UF = "BA"
                        },
                        new
                        {
                            Id = 9,
                            AnoVigencia = 2024,
                            Ativo = true,
                            FonteTJ = "TJ-DF",
                            TipoAto = "Escritura",
                            UF = "DF"
                        },
                        new
                        {
                            Id = 10,
                            AnoVigencia = 2024,
                            Ativo = true,
                            FonteTJ = "TJ-DF",
                            TipoAto = "Registro",
                            UF = "DF"
                        },
                        new
                        {
                            Id = 11,
                            AnoVigencia = 2024,
                            Ativo = true,
                            FonteTJ = "TJ-PR",
                            TipoAto = "Escritura",
                            UF = "PR"
                        },
                        new
                        {
                            Id = 12,
                            AnoVigencia = 2024,
                            Ativo = true,
                            FonteTJ = "TJ-PR",
                            TipoAto = "Registro",
                            UF = "PR"
                        },
                        new
                        {
                            Id = 13,
                            AnoVigencia = 2024,
                            Ativo = true,
                            FonteTJ = "TJ-AM",
                            TipoAto = "Escritura",
                            UF = "AM"
                        },
                        new
                        {
                            Id = 14,
                            AnoVigencia = 2024,
                            Ativo = true,
                            FonteTJ = "TJ-AM",
                            TipoAto = "Registro",
                            UF = "AM"
                        },
                        new
                        {
                            Id = 15,
                            AnoVigencia = 2024,
                            Ativo = true,
                            FonteTJ = "TJ-PE",
                            TipoAto = "Escritura",
                            UF = "PE"
                        },
                        new
                        {
                            Id = 16,
                            AnoVigencia = 2024,
                            Ativo = true,
                            FonteTJ = "TJ-PE",
                            TipoAto = "Registro",
                            UF = "PE"
                        },
                        new
                        {
                            Id = 17,
                            AnoVigencia = 2024,
                            Ativo = true,
                            FonteTJ = "TJ-RS",
                            TipoAto = "Escritura",
                            UF = "RS"
                        },
                        new
                        {
                            Id = 18,
                            AnoVigencia = 2024,
                            Ativo = true,
                            FonteTJ = "TJ-RS",
                            TipoAto = "Registro",
                            UF = "RS"
                        },
                        new
                        {
                            Id = 19,
                            AnoVigencia = 2024,
                            Ativo = true,
                            FonteTJ = "TJ-CE",
                            TipoAto = "Escritura",
                            UF = "CE"
                        },
                        new
                        {
                            Id = 20,
                            AnoVigencia = 2024,
                            Ativo = true,
                            FonteTJ = "TJ-CE",
                            TipoAto = "Registro",
                            UF = "CE"
                        });
                });

            modelBuilder.Entity("ImobiAPI.Domain.Entities.UsoApiKey", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("ApiKeyId")
                        .HasColumnType("integer")
                        .HasColumnName("api_key_id");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("endpoint");

                    b.Property<int>("StatusCode")
                        .HasColumnType("integer")
                        .HasColumnName("status_code");

                    b.HasKey("Id");

                    b.HasIndex("ApiKeyId", "CriadoEm");

                    b.ToTable("uso_api_keys", (string)null);
                });

            modelBuilder.Entity("ImobiAPI.Domain.Entities.AliquotaITBI", b =>
                {
                    b.HasOne("ImobiAPI.Domain.Entities.Municipio", null)
                        .WithOne("AliquotaITBI")
                        .HasForeignKey("ImobiAPI.Domain.Entities.AliquotaITBI", "MunicipioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ImobiAPI.Domain.Entities.FaixaEmolumento", b =>
                {
                    b.HasOne("ImobiAPI.Domain.Entities.TabelaEmolumentos", null)
                        .WithMany("Faixas")
                        .HasForeignKey("TabelaEmolumentosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ImobiAPI.Domain.Entities.Municipio", b =>
                {
                    b.OwnsOne("ImobiAPI.Domain.ValueObjects.CodigoIBGE", "CodigoIBGE", b1 =>
                        {
                            b1.Property<int>("MunicipioId")
                                .HasColumnType("integer");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasMaxLength(7)
                                .HasColumnType("character varying(7)")
                                .HasColumnName("codigo_ibge");

                            b1.HasKey("MunicipioId");

                            b1.HasIndex("Valor")
                                .IsUnique();

                            b1.ToTable("municipios");

                            b1.WithOwner()
                                .HasForeignKey("MunicipioId");

                            b1.HasData(
                                new
                                {
                                    MunicipioId = 1,
                                    Valor = "3550308"
                                },
                                new
                                {
                                    MunicipioId = 2,
                                    Valor = "3304557"
                                },
                                new
                                {
                                    MunicipioId = 3,
                                    Valor = "3106200"
                                },
                                new
                                {
                                    MunicipioId = 4,
                                    Valor = "2927408"
                                },
                                new
                                {
                                    MunicipioId = 5,
                                    Valor = "5300108"
                                },
                                new
                                {
                                    MunicipioId = 6,
                                    Valor = "4106902"
                                },
                                new
                                {
                                    MunicipioId = 7,
                                    Valor = "1302603"
                                },
                                new
                                {
                                    MunicipioId = 8,
                                    Valor = "2611606"
                                },
                                new
                                {
                                    MunicipioId = 9,
                                    Valor = "4314902"
                                },
                                new
                                {
                                    MunicipioId = 10,
                                    Valor = "2304400"
                                });
                        });

                    b.Navigation("CodigoIBGE")
                        .IsRequired();
                });

            modelBuilder.Entity("ImobiAPI.Domain.Entities.UsoApiKey", b =>
                {
                    b.HasOne("ImobiAPI.Domain.Entities.ApiKey", null)
                        .WithMany()
                        .HasForeignKey("ApiKeyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ImobiAPI.Domain.Entities.Municipio", b =>
                {
                    b.Navigation("AliquotaITBI");
                });

            modelBuilder.Entity("ImobiAPI.Domain.Entities.TabelaEmolumentos", b =>
                {
                    b.Navigation("Faixas");
                });
#pragma warning restore 612, 618
        }
    }
}
