// <auto-generated />
using System;
using ImobiAPI.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ImobiAPI.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ImobiAPI.Domain.Entities.AliquotaITBI", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Aliquota")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)")
                        .HasColumnName("aliquota");

                    b.Property<decimal?>("AliquotaFinanciado")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)")
                        .HasColumnName("aliquota_financiado");

                    b.Property<int>("AnoVigencia")
                        .HasColumnType("integer")
                        .HasColumnName("ano_vigencia");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<string>("FonteLegal")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("fonte_legal");

                    b.Property<decimal?>("LimiteIsencao")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("limite_isencao");

                    b.Property<int>("MunicipioId")
                        .HasColumnType("integer")
                        .HasColumnName("municipio_id");

                    b.HasKey("Id");

                    b.HasIndex("MunicipioId")
                        .IsUnique();

                    b.ToTable("aliquotas_itbi", (string)null);
                });

            modelBuilder.Entity("ImobiAPI.Domain.Entities.FaixaEmolumento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("PercentualExcedente")
                        .HasPrecision(6, 4)
                        .HasColumnType("numeric(6,4)")
                        .HasColumnName("percentual_excedente");

                    b.Property<int>("TabelaEmolumentosId")
                        .HasColumnType("integer")
                        .HasColumnName("tabela_id");

                    b.Property<string>("TipoAto")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo_ato");

                    b.Property<decimal>("ValorFixo")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("valor_fixo");

                    b.Property<decimal?>("ValorMaximo")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("valor_maximo");

                    b.Property<decimal>("ValorMinimo")
                        .HasPrecision(15, 2)
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("valor_minimo");

                    b.HasKey("Id");

                    b.HasIndex("TabelaEmolumentosId");

                    b.ToTable("faixas_emolumentos", (string)null);
                });

            modelBuilder.Entity("ImobiAPI.Domain.Entities.Municipio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.Property<int?>("Populacao")
                        .HasColumnType("integer")
                        .HasColumnName("populacao");

                    b.Property<bool>("Suportado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("suportado");

                    b.Property<string>("UF")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("uf");

                    b.HasKey("Id");

                    b.ToTable("municipios", (string)null);
                });

            modelBuilder.Entity("ImobiAPI.Domain.Entities.TabelaEmolumentos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AnoVigencia")
                        .HasColumnType("integer")
                        .HasColumnName("ano_vigencia");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<string>("FonteTJ")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("fonte_tj");

                    b.Property<string>("TipoAto")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo_ato");

                    b.Property<string>("UF")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("uf");

                    b.HasKey("Id");

                    b.HasIndex("UF", "AnoVigencia", "TipoAto")
                        .IsUnique();

                    b.ToTable("tabelas_emolumentos", (string)null);
                });

            modelBuilder.Entity("ImobiAPI.Domain.Entities.AliquotaITBI", b =>
                {
                    b.HasOne("ImobiAPI.Domain.Entities.Municipio", null)
                        .WithOne("AliquotaITBI")
                        .HasForeignKey("ImobiAPI.Domain.Entities.AliquotaITBI", "MunicipioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ImobiAPI.Domain.Entities.FaixaEmolumento", b =>
                {
                    b.HasOne("ImobiAPI.Domain.Entities.TabelaEmolumentos", null)
                        .WithMany("Faixas")
                        .HasForeignKey("TabelaEmolumentosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ImobiAPI.Domain.Entities.Municipio", b =>
                {
                    b.OwnsOne("ImobiAPI.Domain.ValueObjects.CodigoIBGE", "CodigoIBGE", b1 =>
                        {
                            b1.Property<int>("MunicipioId")
                                .HasColumnType("integer");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasMaxLength(7)
                                .HasColumnType("character varying(7)")
                                .HasColumnName("codigo_ibge");

                            b1.HasKey("MunicipioId");

                            b1.HasIndex("Valor")
                                .IsUnique();

                            b1.ToTable("municipios");

                            b1.WithOwner()
                                .HasForeignKey("MunicipioId");
                        });

                    b.Navigation("CodigoIBGE")
                        .IsRequired();
                });

            modelBuilder.Entity("ImobiAPI.Domain.Entities.Municipio", b =>
                {
                    b.Navigation("AliquotaITBI");
                });

            modelBuilder.Entity("ImobiAPI.Domain.Entities.TabelaEmolumentos", b =>
                {
                    b.Navigation("Faixas");
                });
#pragma warning restore 612, 618
        }
    }
}
